require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AdjectivesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Adjective. As you add validations to Adjective, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdjectivesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all adjectives as @adjectives" do
      adjective = Adjective.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:adjectives)).to eq([adjective])
    end
  end

  describe "GET #show" do
    it "assigns the requested adjective as @adjective" do
      adjective = Adjective.create! valid_attributes
      get :show, params: {id: adjective.to_param}, session: valid_session
      expect(assigns(:adjective)).to eq(adjective)
    end
  end

  describe "GET #new" do
    it "assigns a new adjective as @adjective" do
      get :new, params: {}, session: valid_session
      expect(assigns(:adjective)).to be_a_new(Adjective)
    end
  end

  describe "GET #edit" do
    it "assigns the requested adjective as @adjective" do
      adjective = Adjective.create! valid_attributes
      get :edit, params: {id: adjective.to_param}, session: valid_session
      expect(assigns(:adjective)).to eq(adjective)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Adjective" do
        expect {
          post :create, params: {adjective: valid_attributes}, session: valid_session
        }.to change(Adjective, :count).by(1)
      end

      it "assigns a newly created adjective as @adjective" do
        post :create, params: {adjective: valid_attributes}, session: valid_session
        expect(assigns(:adjective)).to be_a(Adjective)
        expect(assigns(:adjective)).to be_persisted
      end

      it "redirects to the created adjective" do
        post :create, params: {adjective: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Adjective.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved adjective as @adjective" do
        post :create, params: {adjective: invalid_attributes}, session: valid_session
        expect(assigns(:adjective)).to be_a_new(Adjective)
      end

      it "re-renders the 'new' template" do
        post :create, params: {adjective: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested adjective" do
        adjective = Adjective.create! valid_attributes
        put :update, params: {id: adjective.to_param, adjective: new_attributes}, session: valid_session
        adjective.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested adjective as @adjective" do
        adjective = Adjective.create! valid_attributes
        put :update, params: {id: adjective.to_param, adjective: valid_attributes}, session: valid_session
        expect(assigns(:adjective)).to eq(adjective)
      end

      it "redirects to the adjective" do
        adjective = Adjective.create! valid_attributes
        put :update, params: {id: adjective.to_param, adjective: valid_attributes}, session: valid_session
        expect(response).to redirect_to(adjective)
      end
    end

    context "with invalid params" do
      it "assigns the adjective as @adjective" do
        adjective = Adjective.create! valid_attributes
        put :update, params: {id: adjective.to_param, adjective: invalid_attributes}, session: valid_session
        expect(assigns(:adjective)).to eq(adjective)
      end

      it "re-renders the 'edit' template" do
        adjective = Adjective.create! valid_attributes
        put :update, params: {id: adjective.to_param, adjective: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested adjective" do
      adjective = Adjective.create! valid_attributes
      expect {
        delete :destroy, params: {id: adjective.to_param}, session: valid_session
      }.to change(Adjective, :count).by(-1)
    end

    it "redirects to the adjectives list" do
      adjective = Adjective.create! valid_attributes
      delete :destroy, params: {id: adjective.to_param}, session: valid_session
      expect(response).to redirect_to(adjectives_url)
    end
  end

end
